### ISSUE TITLE
Handle return array

### ISSUE THREAD

**Issue by Erliz** [adrenth/thetvdb#6]
As i understand `SeriesResponseHandler` should return `SeriesResponse` but if there are series in xml response it return just an array
I alredy fix it just with replace array to `SeriesResponse`, but it will breake backwards compatibility with thouse who use return `SeriesResponseHandler::handle` as array. So i suggest to implement ArrayAccess and Traversable for gracefull fix this bug.
I think its easy to implement [Doctrine\Common\Collections\ArrayCollection](http://www.doctrine-project.org/api/common/2.1/class-Doctrine.Common.Collections.ArrayCollection.html) but it`s need another dependence for project.
What do you think?

**Comment by adrenth** [comment]
Thanks for your thought on that, but I want to focus on branch 2.0 and stop developing on version 0.1. So feel free to make any modifications on this issue, and i'll release this a 0.2 version.
